"""Alter invite token column

Revision ID: 1d1422eca2ba
Revises: 77a7e28ba9dc
Create Date: 2016-02-23 10:49:33.116000

"""

# revision identifiers, used by Alembic.
revision = '1d1422eca2ba'
down_revision = '77a7e28ba9dc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invitation', 'token',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=32),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invitation', 'token',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    ### end Alembic commands ###
